import = ["/Users/yasin/.config/alacritty/themes/themes/tokyo-night-storm.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 16
# offset = { y = 20 }
# glyph_offset = { y = 10 }
normal = { family = "CaskaydiaCove Nerd Font" }

[window]
opacity = 0.9
blur = true
option_as_alt = "Both"
dimensions = { columns = 150, lines = 30 }
