import = ["~/.config/alacritty/catppuccin-frappe.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 16
offset = { y = 12 }
glyph_offset = { y = 6 }
normal = { family = "CaskaydiaCove Nerd Font Mono" }

[window]
opacity = 0.9
blur = true
option_as_alt = "Both"
dimensions = { columns = 135, lines = 45 }
decorations = "Buttonless"
