# Improve colors
set -g default-terminal "${TERM}"
set -ag terminal-overrides ",xterm-256color:RGB"

# mouse support
set -g mouse on

# change prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# renumber windows when one is removed
set -g renumber-windows on

# open panes in current directory
bind '-' split-window -v -c "#{pane_current_path}"
bind '|' split-window -h -c "#{pane_current_path}"

# Navigating between pane like vim
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# reload config
bind R source-file ~/.config/tmux/tmux.conf\; display-message 'Tmux config reloaded!'

# statusline
set -g status-position top
set -g @catppuccin_flavour 'frappe' # latte, frappe, macchiato, mocha
set -g @catppuccin_window_status_enable "yes"
set -g @catppuccin_icon_window_last ""
set -g @catppuccin_icon_window_current ""
set -g @catppuccin_icon_window_mark "󰃀"
set -g @catppuccin_window_left_separator " █"
set -g @catppuccin_window_right_separator "█"
set -g @catppuccin_window_number_position "left"
set -g @catppuccin_window_middle_separator "  "
set -g @catppuccin_window_default_fill "none"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "all"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_status_modules_left "session"
set -g @catppuccin_status_modules_right "directory date_time"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"
set -g @catppuccin_directory_text "#{pane_current_path}"
set -g @catppuccin_date_time_text "%Y-%m-%d %H:%M"
set -g @catppuccin_session_icon "󰭹"
set -g @catppuccin_directory_icon ""

# pugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'catppuccin/tmux'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
